version: 2.1

executors:
  linode-executor:
    machine: true # Full virtual machine executor for deployment

jobs:
  build:
    executor: linode-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update -y
            sudo apt install -y curl git build-essential
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install lts/hydrogen
            nvm use lts/hydrogen
            npm install
      - run:
          name: Run Tests
          command: npm test

  deploy:
    executor: linode-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:15gnNQL/pbFECNggwr1dWXFjd2IdQVc2db8bcw/fSVw" # Replace with your CircleCI SSH key fingerprint
      - run:
          name: Deploy Application
          command: |
            ssh root@172.235.61.127  "
              cd /root/canvas2 || { echo 'Directory not found'; exit 1; }
              git pull origin main || { echo 'Git pull failed'; exit 1; }
              npm install || { echo 'NPM install failed'; exit 1; }
              pm2 restart all || { echo 'PM2 restart failed'; exit 1; }
            "

workflows:
  deploy-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main # Replace with your branch name
